# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hanzhe(object):
    def setupUi(self, hanzhe):
        hanzhe.setObjectName("hanzhe")
        hanzhe.resize(739, 587)
        hanzhe.setMinimumSize(QtCore.QSize(251, 291))
        self.gridLayout = QtWidgets.QGridLayout(hanzhe)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(hanzhe)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"   border: none;\n"
"   background-color: transparent;\n"
"}\n"
"")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(hanzhe)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"   border: none;\n"
"   background-color: transparent;\n"
"}\n"
"")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(hanzhe)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"   border: none;\n"
"   background-color: transparent;\n"
"}\n"
"")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(hanzhe)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"   border: none;\n"
"   background-color: transparent;\n"
"}\n"
"")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(hanzhe)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"   border: none;\n"
"   background-color: transparent;\n"
"}\n"
"")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(hanzhe)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"   border: none;\n"
"   background-color: transparent;\n"
"}\n"
"")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.recognition = QtWidgets.QPushButton(hanzhe)
        self.recognition.setMinimumSize(QtCore.QSize(0, 90))
        self.recognition.setObjectName("recognition")
        self.verticalLayout.addWidget(self.recognition)
        self.verticalLayout.setStretch(6, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(4, 1, -1, 3)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.apple = QtWidgets.QLineEdit(hanzhe)
        self.apple.setMinimumSize(QtCore.QSize(0, 50))
        self.apple.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.apple.setObjectName("apple")
        self.verticalLayout_2.addWidget(self.apple)
        self.banana = QtWidgets.QLineEdit(hanzhe)
        self.banana.setMinimumSize(QtCore.QSize(0, 50))
        self.banana.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.banana.setObjectName("banana")
        self.verticalLayout_2.addWidget(self.banana)
        self.watermelon = QtWidgets.QLineEdit(hanzhe)
        self.watermelon.setMinimumSize(QtCore.QSize(0, 50))
        self.watermelon.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.watermelon.setObjectName("watermelon")
        self.verticalLayout_2.addWidget(self.watermelon)
        self.kg = QtWidgets.QLineEdit(hanzhe)
        self.kg.setMinimumSize(QtCore.QSize(0, 50))
        self.kg.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.kg.setObjectName("kg")
        self.verticalLayout_2.addWidget(self.kg)
        self.recognize = QtWidgets.QLineEdit(hanzhe)
        self.recognize.setMinimumSize(QtCore.QSize(0, 50))
        self.recognize.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.recognize.setReadOnly(True)
        self.recognize.setPlaceholderText("")
        self.recognize.setObjectName("recognize")
        self.verticalLayout_2.addWidget(self.recognize)
        self.result = QtWidgets.QLineEdit(hanzhe)
        self.result.setMinimumSize(QtCore.QSize(0, 50))
        self.result.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"}\n"
"")
        self.result.setInputMask("")
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.verticalLayout_2.addWidget(self.result)
        self.choose = QtWidgets.QPushButton(hanzhe)
        self.choose.setMinimumSize(QtCore.QSize(0, 50))
        self.choose.setObjectName("choose")
        self.verticalLayout_2.addWidget(self.choose)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(hanzhe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(350, 250))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)

        self.retranslateUi(hanzhe)
        QtCore.QMetaObject.connectSlotsByName(hanzhe)

    def retranslateUi(self, hanzhe):
        _translate = QtCore.QCoreApplication.translate
        hanzhe.setWindowTitle(_translate("hanzhe", "Form"))
        self.lineEdit.setText(_translate("hanzhe", "苹果："))
        self.lineEdit_2.setText(_translate("hanzhe", "香蕉："))
        self.lineEdit_3.setText(_translate("hanzhe", "西瓜："))
        self.lineEdit_4.setText(_translate("hanzhe", "重量："))
        self.lineEdit_5.setText(_translate("hanzhe", "识别："))
        self.lineEdit_6.setText(_translate("hanzhe", "总价："))
        self.recognition.setText(_translate("hanzhe", "计重"))
        self.choose.setText(_translate("hanzhe", "选择+识别"))
